export default {
  UPDATE_SELECTED_LESSONS_REQUEST : "UPDATE_SELECTED_LESSONS_REQUEST",
  UPDATE_SELECTED_LESSONS_SUCCESS : "UPDATE_SELECTED_LESSONS_SUCCESS",
  UPDATE_SELECTED_LESSONS_FAILURE : "UPDATE_SELECTED_LESSONS_FAILURE",
}